# Generated by Django 3.2.7 on 2021-10-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_newslettersubscribermodel_newslettersubscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribers',
            new_name='NewsletterSubscriber',
        ),
    ]
