# Generated by Django 3.2.7 on 2021-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_zssjmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAIPARBookshelfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.IntegerField(blank=True, verbose_name=((0, 'eBook'), (1, 'eArticle'), (2, 'print')))),
                ('downloadable', models.BooleanField(default=False)),
                ('link', models.FileField(blank=True, upload_to='static/publications/SAIPAR_bookshelf')),
                ('price', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
