# Generated by Django 3.2.7 on 2021-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_saiparbookshelfmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saiparbookshelfmodel',
            name='book_type',
            field=models.IntegerField(blank=True, choices=[(0, 'eBook'), (1, 'eArticle'), (2, 'print')]),
        ),
    ]
