# Generated by Django 3.2.7 on 2022-02-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0005_alter_reportsmodel_paper_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saiparbookshelfmodel',
            name='link',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
