# Generated by Django 3.2.7 on 2022-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0006_alter_saiparbookshelfmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpapersmodel',
            name='paper_link',
            field=models.FileField(blank=True, upload_to='publications/discussion_papers'),
        ),
        migrations.AlterField(
            model_name='ocasionalpapermodel',
            name='paper_link',
            field=models.FileField(blank=True, upload_to='publications/occassional_papers'),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='paper_link',
            field=models.FileField(blank=True, upload_to='publications/reports_and_policy_briefs'),
        ),
        migrations.AlterField(
            model_name='saiparbookshelfmodel',
            name='link',
            field=models.FileField(blank=True, upload_to='publications/SAIPAR_bookshelf'),
        ),
        migrations.AlterField(
            model_name='zssjmodel',
            name='link',
            field=models.FileField(blank=True, upload_to='publications/zssj'),
        ),
    ]
