# Generated by Django 3.2.7 on 2022-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0007_auto_20220204_0548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OcasionalPaperModel',
            new_name='OccasionalPaperModel',
        ),
    ]
