# Generated by Django 3.2.5 on 2021-07-31 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStaff',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.staff')),
                ('bio', models.TextField()),
                ('institution', models.CharField(max_length=50)),
            ],
            bases=('people.staff',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('researchstaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.researchstaff')),
                ('title', models.CharField(max_length=60)),
            ],
            bases=('people.researchstaff',),
        ),
    ]
