# Generated by Django 3.2.7 on 2021-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchstaff',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='researchstaff',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AddField(
            model_name='researchstaff',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Research Staff'), (2, 'Research Affiliate'), (3, 'SAIPAR Fellows'), (4, 'Robert Kent Fellows'), (5, 'Interns')], default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='affiliation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='committee',
            field=models.IntegerField(blank=True, choices=[(1, 'Executive'), (2, 'Audit')], null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='director',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='iab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/people'),
        ),
        migrations.AddField(
            model_name='staff',
            name='institution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
