# Generated by Django 3.2.7 on 2021-10-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_iab_staff_international_advisory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchstaff',
            name='research_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Research Staff'), (2, 'Research Affiliate'), (3, 'SAIPAR Fellow'), (4, 'Robert Kent Fellow'), (5, 'Intern')], default=0),
        ),
    ]
