# Generated by Django 3.2.7 on 2021-10-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/people'),
        ),
    ]
