# Generated by Django 3.2.7 on 2022-01-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_staff_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchstaff',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('name',)},
        ),
    ]
