# Generated by Django 3.2.7 on 2021-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPoliticalChangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
