# Generated by Django 3.2.7 on 2022-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpoliticalchangemodel',
            name='upload_link',
            field=models.FileField(blank=True, default=None, upload_to='programs/social_political_change'),
        ),
        migrations.AlterField(
            model_name='socialpoliticalchangemodel',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
