# Generated by Django 3.2.7 on 2022-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20220207_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpoliticalchangemodel',
            name='upload_link',
            field=models.FileField(blank=True, null=True, upload_to='programs/social_political_change'),
        ),
    ]
