# Generated by Django 3.2.7 on 2021-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
