# Generated by Django 3.2.7 on 2021-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20211016_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
