# Generated by Django 3.2.7 on 2021-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_projectmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
