# Generated by Django 3.2.7 on 2022-01-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_eventmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ('date', 'time')},
        ),
    ]
