# Generated by Django 3.2.7 on 2022-01-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_eventmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ('-date', '-time')},
        ),
    ]
