# Generated by Django 3.2.7 on 2022-01-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_eventmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='static/events-and-resources'),
        ),
    ]
