# Generated by Django 3.2.7 on 2022-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_eventmodel_upload_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
