# Generated by Django 3.2.7 on 2022-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_eventmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='static/events&resources'),
        ),
    ]
