# Generated by Django 3.2.7 on 2022-01-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_eventmodel_upload_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ('-date',)},
        ),
    ]
