# Generated by Django 3.2.7 on 2022-01-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_projectmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ('date',)},
        ),
    ]
