# Generated by Django 3.2.7 on 2022-02-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_projectmodel_upload_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='events&resources/openings'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='events&resources/events'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='events&resources/projects'),
        ),
    ]
