# Generated by Django 3.2.7 on 2022-02-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20220207_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='resources/events'),
        ),
        migrations.AlterField(
            model_name='openingmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='resources/openings'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='upload_link',
            field=models.FileField(blank=True, upload_to='resources/projects'),
        ),
    ]
